### ISSUE TITLE
Clean-up Copier prompt questions in copier.yml

### ISSUE THREAD

**Issue by kefeimo** [VOLTTRON/copier-poetry-volttron-agent#21]
ref: [Configuring a template](https://copier.readthedocs.io/en/latest/configuring/)
e.g., configure default options to improve ease of use.

**Comment by kefeimo** [comment]
Fixed by PR #31.
Manually closed

**Comment by kefeimo** [comment]
Similar to the following code in `copier.yml`
```
use_precommit:
  type: bool
  help: Do you want to use pre-commit?
  default: no
```
There should be counter part: `use_codeql`, `use_mypi`, etc.
